### ISSUE TITLE
Promises in the future

### ISSUE THREAD

**Issue by marcosdourado** [kolbasa/cordova-plugin-apkupdater#1]
I didn't see any roadmap, so I ask here.
Is there an intention to use or offer promises in the future?

**Comment by kolbasa** [comment]
Thanks for the suggestion. Sounds good to me. I'll make it happen this week! :+1:

**Comment by kolbasa** [comment]
It is now implemented on this [branch](https://github.com/kolbasa/cordova-plugin-apkupdater/tree/promises-api). 

I need to test it for a while. Tomorrow it will be merged into the master.
