### ISSUE TITLE
App Not Installed

### ISSUE THREAD

**Issue by jjacobs33589** [kolbasa/cordova-plugin-apkupdater#10]
I have the following in my app to check for android updates and download if available.

```
const manifest = await cordova.plugins.apkupdater.check(environment.updateUrl);
        if (manifest.version !== this.appService.getInstalledApplicationVersion()) {
            console.log('Android Update Available');
            await cordova.plugins.apkupdater.download();
            await cordova.plugins.apkupdater.install();
            
        } else {
            console.log('No Android update available');
        }
```

The app sees that an update is available and it downloads it successfully. 
It brings up the screen asking if I want to update the existing application.

However, when I click Install, it tries for a couple seconds then says 'App Not Installed'.

I'm not sure how to get any error logs or anything that might tell me why it's not working. Do you have any recommendations I can try to get it to work?

**Comment by kolbasa** [comment]
This should be a problem with your update apk file.

I would first just try to install the update with adb-tools.
There you also find out the reason why the update fails.

I can spontaneously think of two reasons.
The apk signature has changed or the version was downgraded (which is not allowed).

First you should install the app you want to update as usual. And then the update is installed via adb:
```bash
adb install path-to-your.apk
```

This then provides the cause. Here are two example outputs:
```
adb: failed to install apk-updater-demo.apk: Failure [INSTALL_FAILED_VERSION_DOWNGRADE]
```
```
adb: failed to install apk-updater-demo.apk: Failure [INSTALL_FAILED_UPDATE_INCOMPATIBLE:  Package de.kolbasa.apkupdater signatures do not match previously installed version; ignoring!]
```

Please let me know if this helps. Maybe I should improve the documentation at this point.

**Comment by jjacobs33589** [comment]
Yes, this helps a lot! Thank you. I think I've got it figured out
