### ISSUE TITLE
direct Installation without  prompt

### ISSUE THREAD

**Issue by starhu521** [kolbasa/cordova-plugin-apkupdater#13]
Hello, I want to know it's possible to installation directly without prompt?

**Comment by kolbasa** [comment]
Unfortunately, this is not possible. The prompt is from Android itself. The user must approve the installation.

**Comment by starhu521** [comment]
> Unfortunately, this is not possible. The prompt is from Android itself. The user must approve the installation.

Thanks for your apply. And I'm not a android developer, but I find maybe it's pissible for android 6. Can you give me some advice ?

**Comment by kolbasa** [comment]
This will not work on Android 6 either. 
But what could help you is: [code-push](https://github.com/Microsoft/cordova-plugin-code-push). 
This will automatically update HTML, JavaScript, CSS and assets like image and soundfiles.

But if you want to install a new native Cordova plugin in the future, then you need to update the apk and prompt the user accordingly.

In my project it is done the same way. 90% of the updates is pure HTML+JS+CSS and is swapped automatically, for the other 10% you have to ask the user.
But if your app uses fewer hardware features, then maybe 100% of all updates can work that way.

**Comment by starhu521** [comment]
> This will not work on Android 6 either.
> But what could help you is: [code-push](https://github.com/Microsoft/cordova-plugin-code-push).
> This will automatically update HTML, JavaScript, CSS and assets like image and soundfiles.
> 
> But if you want to install a new native Cordova plugin in the future, then you need to update the apk and prompt the user accordingly.
> 
> In my project it is done the same way. 90% of the updates is pure HTML+JS+CSS and is swapped automatically, for the other 10% you have to ask the user.
> But if your app uses fewer hardware features, then maybe 100% of all updates can work that way.

Thanks. I need find another way.

**Comment by danielehrhardt** [comment]
I need the same. 
Would it be possible with root or device Admin?

**Comment by kolbasa** [comment]
Yes, it should be possible with a rooted device.
I'll try it out on the weekend.

**Comment by danielehrhardt** [comment]
> Yes, it should be possible with a rooted device.
> I'll try it out on the weekend.

This would be nice!
I am also a Device Admin.

**Comment by starhu521** [comment]
> Yes, it should be possible with a rooted device.
> I'll try it out on the weekend.

Hello, I am back again. Is it different between the rooted device and the signed app with system key? If it's possible, can you try that app signed with system key as system app?

**Comment by kolbasa** [comment]
I will be looking at both this weekend.

**Comment by kolbasa** [comment]
I have tried it now. Seems to work very well.
The update can be installed automatically with root privileges. After installation, the app will also restart automatically.

I need some time now to implement this correctly.
I will probably introduce three new methods:

```
hasRootPrivileges()
requestRootPrivileges()
rootInstall()
```

Then it is up to you when to ask for root privileges.

@starhu521
As I understand it, this will also work for system apps, except that it won't ask for root privileges in the first place.

![Root Install](https://user-images.githubusercontent.com/3901582/106362084-3b9abf80-6321-11eb-8e37-becd08588ba2.gif)

**Comment by danielehrhardt** [comment]
> Then it is up to you when to ask for root privileges.

Really nice! 
Do you have some sample code to test?

**Comment by kolbasa** [comment]
Here is a prototype:
https://github.com/kolbasa/cordova-plugin-apkupdater/tree/root-installation

At the moment there is only one new method:
```js
await cordova.plugins.apkupdater.rootInstall();
```

This also throws an error if no root privileges are present.

**Comment by danielehrhardt** [comment]
> https://github.com/kolbasa/cordova-plugin-apkupdater/tree/root-installation

You're the best!

**Comment by kolbasa** [comment]
Thanks for the tip.
It's fixed now.

**Comment by starhu521** [comment]
> I have tried it now. Seems to work very well.
> The update can be installed automatically with root privileges. After installation, the app will also restart automatically.
> 
> I need some time now to implement this correctly.
> I will probably introduce three new methods:
> 
> ```
> hasRootPrivileges()
> requestRootPrivileges()
> rootInstall()
> ```
> 
> Then it is up to you when to ask for root privileges.
> 
> @starhu521
> As I understand it, this will also work for system apps, except that it won't ask for root privileges in the first place.
> 
> ![Root Install](https://user-images.githubusercontent.com/3901582/106362084-3b9abf80-6321-11eb-8e37-becd08588ba2.gif)

Thank you very much! I will try it.

**Comment by starhu521** [comment]
@kolbasa  Hello! This method of "su pm" can't work in the device that just is signed with (system key: pk8 and pem) without root. Devices signed with system can use  packageManager.installPackage.

**Comment by kolbasa** [comment]
Thanks for the info. I will read up on how to sign an app as a system app. 
I will test it this weekend.

**Comment by kolbasa** [comment]
I'll close this for now.

I'm starting to work on the project again now. I also already have some prototype code for Device Admins permissions.
You can then watch here as soon as I start to bring everything together:
https://github.com/kolbasa/cordova-plugin-apkupdater/projects/9

**Comment by danielehrhardt** [comment]
> I'll close this for now.
> 
> I'm starting to work on the project again now. I also already have some prototype code for Device Admins permissions.
> You can then watch here as soon as I start to bring everything together:
> https://github.com/kolbasa/cordova-plugin-apkupdater/projects/9

What was the outcome  with Device Admin Permission?

**Comment by kolbasa** [comment]
Sorry for the delay. I have time for it now and am already looking at how I can implement it.

**Comment by kolbasa** [comment]
Progress:

![device_owner_install](https://user-images.githubusercontent.com/3901582/127506520-9bac921f-11e4-4f43-bef8-8e1757a83c5e.gif)

**Comment by danielehrhardt** [comment]
> Progress:
> 
> ![device_owner_install](https://user-images.githubusercontent.com/3901582/127506520-9bac921f-11e4-4f43-bef8-8e1757a83c5e.gif)

Really nice !!

**Comment by kolbasa** [comment]
I have now added two new functions: `isDeviceOwner()` and `ownerInstall()` on the branch `device-owner-installation`.
```
cordova plugin add https://github.com/kolbasa/cordova-plugin-apkupdater#device-owner-installation
```

The app is now also automatically reloaded after installation.
In my case I set the device owner status to the app via `adb shell`.
It would be nice if you could give me feedback on whether this is sufficient. I'm still quite unsure, since I don't know exactly how this is managed in a productive setting.

I have tested it with Android 11 and 12. It works without any problems there.

![device_owner_install](https://user-images.githubusercontent.com/3901582/127636842-52adbf41-3b9e-4b82-a270-05b260ae65dd.gif)

**Comment by kolbasa** [comment]
It is now released in the `2.3.0` version. 

People who already have a device owner app can use this install method.
I will soon push a separate plugin that helps to set up such an app. But that is outside the scope of the updater plugin.

**Comment by danielehrhardt** [comment]
> It is now released in the `2.3.0` version.
> 
> People who already have a device owner app can use this install method.
> I will soon push a separate plugin that helps to set up such an app. But that is outside the scope of the updater plugin.

You Rock!

**Comment by danielehrhardt** [comment]
> It is now released in the `2.3.0` version.
> 
> People who already have a device owner app can use this install method.
> I will soon push a separate plugin that helps to set up such an app. But that is outside the scope of the updater plugin.

I am getting 
```
message: App is not device owner, 
stack: 
java.lang.SecurityException: App is not device owner
```

I am setting the device owner with the following app:
https://github.com/smartbell-codext/cordova-plugin-deviceadmin
Do you know what permission is missing here?:
https://github.com/smartbell-codext/cordova-plugin-deviceadmin/blob/master/src/android/deviceadmin.xml

**Comment by kolbasa** [comment]
You are confusing "Device Admin" with "Device Owner" here. 
Or I misunderstood the initial feature request 💩 . 

A device admin cannot perform silent updates.
The `register` method of the `cordova-plugin-deviceadmin` makes the app a device admin.
With the adb command you make the app the owner.

As I understand it, the device owner status can also be achieved with the
Android Management API. But there I don't know exactly which hurdles you have to jump over.

So the methods are useful for all users who have physical access to the device, but do not want to root a device.
For this case I want to push a similar plugin like `cordova-plugin-deviceadmin`, only stripped down, only for the DeviceOwnerReceiver file for the Adb command.

**Comment by danielehrhardt** [comment]
Ah ok my mistake. Did not know that there is a difference. I thought it was the same 🙈 

Is it possible to get Device Owner on the device without adb?

**Comment by kolbasa** [comment]
There are three other options, as far as I know:
* The official way is via Google: https://developers.google.com/android/management/provision-device
* You sign the app with platform keys.
* Root access can also set the owner flag (but then you could also just use root directly to install).

**Comment by kolbasa** [comment]
I have now adjusted the documentation. The device owner can now be set without an additional plugin.

**Comment by software-OSG** [comment]
Hello @kolbasa 

Great 3.0.0 Release
Thank you
