### ISSUE TITLE
Customize installation prompt

### ISSUE THREAD

**Issue by lupodellasleppa** [kolbasa/cordova-plugin-apkupdater#16]
Hello and kudos on the great plugin!

Just wanted to ask if there's a possibility to customize the installation prompt, or, if that is not possible, to at least translate the message? Thanks!

**Comment by kolbasa** [comment]
The plugin does not provide its own installation dialog. So you can design it the way you want. 
Below you can see an example of a real use of the plugin. This app also offers multiple languages:

![Bildschirmfoto 2021-04-12 um 12 58 17](https://user-images.githubusercontent.com/3901582/114384674-54301d00-9b8f-11eb-960c-447a97958432.png)

![Bildschirmfoto 2021-04-12 um 13 02 58](https://user-images.githubusercontent.com/3901582/114384752-6e69fb00-9b8f-11eb-91fc-6470891a4eb4.png)

**Comment by lupodellasleppa** [comment]
Thank you for the quick reply!

I am so sorry, I was sure I read this sentence

> **By design, the plugin does not provide its own update dialogs.**

somewhere in the README but this morning I was in a rush and missed it.

So I am guessing the prompt I'm seeing is the default system prompt.

I'm closing the issue, thanks again!
