### ISSUE TITLE
SUPORT IONIC V3

### ISSUE THREAD

**Issue by aldrigo** [kolbasa/cordova-plugin-apkupdater#17]
THIS PLUGIN HAS SUPPORT FOR IONIC V3, HOW TO USE? 

I AM RETURNING =  ReferenceError: apkupdater is not defined

SORRY FOR MY ENGLISH

**Comment by kolbasa** [comment]
Sorry for the delay.
Ionic V3 supports Cordova, so you can also use this plugin.
However, at the moment I can't tell you exactly how to install plugins specifically in Ionic 3. You should be able to find enough examples in the Ionic documentation.

**Comment by kolbasa** [comment]
Version `2.2.0` now has its own TypeScript API:

```ts
import ApkUpdater from 'cordova-plugin-apkupdater';

export class HomePage {

    // .
    // .
    // .

    async update() {
        await ApkUpdater.download(
            'https://your-update-server.com/update.apk',
            {
                onDownloadProgress: progress => console.log,
            }
        );
        await ApkUpdater.install();
    }

}
```
