### ISSUE TITLE
Install() not workin app-release.apk

### ISSUE THREAD

**Issue by leoalemao3** [kolbasa/cordova-plugin-apkupdater#18]
install works if the apk understood for app-debug.apk, if the apk understood for app-release.apk does not install,

**Comment by kolbasa** [comment]
Sorry for the delay. I didn't pay attention to my notifications.
You can only update apps if the signature has remained unchanged and the app version has been correctly raised accordingly.
So you can't update an "app-debug.apk" with an "app-release.apk".

Here you can find some more hints:
https://github.com/kolbasa/cordova-plugin-apkupdater/issues/10

**Comment by aldrigo** [comment]
Thanks for the feedback! that was the same problem, if I install a release.apk and try to upgrade to another release.apk it works


your plugin saved my project 

att tks
