### ISSUE TITLE
Capacitor

### ISSUE THREAD

**Issue by nadj** [kolbasa/cordova-plugin-apkupdater#2]
Hi @kolbasa, I would like to test your plugin on my app built with capacitor. 
Do you have in plan to port it?

Thanks in advance

**Comment by kolbasa** [comment]
If there is a need, I will do it. I have a lot of time :D.
I'm gonna read up on everything I need to know about Capacitor and then I will port the plugin. :+1:

**Comment by nadj** [comment]
Thanks

**Comment by danielehrhardt** [comment]
Would be Amazing!!

**Comment by danielehrhardt** [comment]
![image](https://user-images.githubusercontent.com/19570043/87153594-03b22900-c2b8-11ea-9186-433ad351b707.png)

Fyi:
I use capacitor. 
Instead of
import android.support.v4.content.FileProvider;
I Import:
import androidx.core.content.FileProvider;

**Comment by kolbasa** [comment]
Thanks for the hint. I will change it. :+1:

**Comment by kolbasa** [comment]
As you can see, I didn't have as much time as I thought. 
But now I start working on it again. I guess I need 2-3 weeks for a capacitor port, because I only do it on the side.

You will be able to observe the progress here:
https://github.com/kolbasa/cordova-plugin-apkupdater/projects/6

**Comment by jjacobs33589** [comment]
Is this still in progress? 
I've been using this plugin for my cordova app for a few months and it's amazing. 
I'm in the process of converting my app from cordova to capacitor and am wondering if I can still use this plugin?

**Comment by danielehrhardt** [comment]
> Is this still in progress?
> I've been using this plugin for my cordova app for a few months and it's amazing.
> I'm in the process of converting my app from cordova to capacitor and am wondering if I can still use this plugin?

Does work without any problems

**Comment by jjacobs33589** [comment]
How do you use it with capacitor?
