### ISSUE TITLE
Separate manifest.json and download path (and add optional data?)

### ISSUE THREAD

**Issue by patrickbussmann** [kolbasa/cordova-plugin-apkupdater#20]
Thank you very much for this plugin @kolbasa.
But I now have a workflow which is a bit different from your great working but simple workflow.

Is it possible to do this?

**1.) Adding optional (POST body) parameters to query**

Current situation is:

```
await cordova.plugins.apkupdater.check('https://your-domain.com/update/manifest.json');
```

My idea would be like this:

```
await cordova.plugins.apkupdater.check('https://your-domain.com/update/manifest.json', {
    currentVersion: '1.2.3',
    deviceStatus: 'Healthy',
    battery: 100.0
});
```

Why?
I want to use the APK Updater for a platform which is similar to device management.
So I need a list of all devices with their versions and status.
Currently I'm having two requests. One for the APK Updater to check the version and one to tell the server the status of the device.
Would be nice.

And I could imagine that some servers can generate special versions based on the input.

As fallback I can extend the URL with query parameters like:

    https://your-domain.com/update/manifest.json?currentVersion=1.2.3&deviceStatus=Healthy&battery=100.0

**2.) Define remote path to the update (for example S3)**

Currently its like you have a folder with few files.

    https://your-domain.com/update/

And there you have for example:

- manifest.json
- update.zip.001
- update.zip.002
- update.zip.003

But now we imagine about a microservice endpoint which not contains files - only logic.
So we want to specify for example a S3 endpoint for downloading.

So we want to extend the manifest.json response like:

```
{
  "version": "1.0.0",                        // your custom version
  "sum": "35d9fd2d688156e45b89707f650a61ac", // checksum of the apk-file
  "size": 5425986,                           // size of the apk-file
  "compressedSize": 4304842,                 // size of the compressed update
  "chunks": [
    "bf0b504ea0f6cdd7d3ba20d2fff48870",      // checksum of "update.zip.001"
    "830d523f8f2038fea5ae0fccb3dfa4c0",      // checksum of "update.zip.002"
    "c6a744ca828fa6dff4de888c6ec79a38"       // checksum of "update.zip.003"
  ],
  "paths": [
    "https://example-app-update-storage-12345678.s3.eu-central-1.amazonaws.com/1.0.0/update.zip.001",
    "https://example-app-update-storage-12345678.s3.eu-central-1.amazonaws.com/1.0.0/update.zip.002",
    "https://example-app-update-storage-12345678.s3.eu-central-1.amazonaws.com/1.0.0/update.zip.003"
  ]
}
```

Then we can have the update files separated and its like an CDN.

Fallback solution is to check the version manually. Then use your plugin with special endpoint and route the update files to S3 via redirect.

Maybe there are other people's who are happy about this improvements, too.

I can start to work on a PR if this is welcome 😊

**Comment by kolbasa** [comment]
Hello, thank you for the suggestions for improvement. And thank you for such a detailed description. :)

I'm in the process of working on improvements, so this comes at the right time.

On the first point with the post body:
I don't need to think much about it, it sounds sensible, I'm sure many could use it.

On the second point:
Sounds sensible too, I would directly take that and implement it as well. The original idea was to keep the manifest as small as possible, but it can't hurt to make modifying paths optional.

For my understanding, a few more questions: 

- Does that mean that the manifest and the associated paths are then provided on demand by your api?
- Are the paths invalidated by time?

I would like to improve the error handling of the plugin in one of the next updates. For this, such information would be great.

I have reserved time for the plugin over the weekend. I guess on Monday both changes will be ready for testing on a branch.

**Comment by patrickbussmann** [comment]
Thank you very much @kolbasa 🥳
Its not time critical and I can continue on your branch when you want 👍 

Reply to your questions:

- Does that mean that the manifest and the associated paths are then provided on demand by your api?

Yes I realize with an API which gets the S3 path from database.
But in theory you can imagine a static provided manifest.json.

For example you have the manifest on your website:

    https://update.your-domain.com/manifest.json

**And then the paths within:**

```
{
  [...]
  "paths": [
    "https://cdn.your-domain.com/update.zip.001",
    "https://cdn.your-domain.com/update.zip.002",
    "https://cdn.your-domain.com/update.zip.003"
  ]
}
```

In theory you can put the manifest.json in the same folder but imagine you have a caching system.
Then you can specify it a bit more:

    https://update.your-domain.com/manifest.json?currentTime=1622751336

**Results in:**

```
{
  [...]
  "version": "1.2.3",
  "paths": [
    "https://cdn.your-domain.com/1.2.3/update.zip.001",
    "https://cdn.your-domain.com/1.2.3/update.zip.002",
    "https://cdn.your-domain.com/1.2.3/update.zip.003"
  ]
}
```

- Are the paths invalidated by time?

In my case the paths will be changed with each update.
So manifest.json points only to the current ( = newest ) version.
The old folders will be deleted after few months. (version history)

It would be ok, too when you only specify one path:

```
{
  [...]
  "version": "1.2.3",
  "path": "https://cdn.your-domain.com/1.2.3" // <- here you have then files like update.zip.001 update.zip.002 update.zip.003
}
```


😊

**Comment by kolbasa** [comment]
Sorry for the delay.

I started working and then realized that it didn't make sense at all.
The plugin is the wrong place to send POST-requests.
I have completely rewritten the plugin. There is no manifest logic anymore, no `check`-method.

In short, only a `download` and `install` method is offered (and some helper methods).

I still have to write a proper documentation, but on the `refactoring`-branch you can already test the version.

`v2.0.0`:
https://github.com/kolbasa/cordova-plugin-apkupdater/tree/refactoring

Demo-Apk:
https://github.com/kolbasa/cordova-plugin-apkupdater-demo

**Comment by kolbasa** [comment]
I think I can close this now. Let me know if you have problems with the new version.
