### ISSUE TITLE
Upload whole APKs instead of chunked ZIP files

### ISSUE THREAD

**Issue by capc0** [kolbasa/cordova-plugin-apkupdater#21]
It would be nice if the chunked mechanism is optional and the update also works with just a new APK file.

Common use case:

All versions of an app are stored on a webserver as APK files. The user can download any (preferable the latest version directly from the server as an APK), and the updater checks (via the manifest file) if there is a newer APK on the webserver.

**Comment by kolbasa** [comment]
The basic idea is actually just that the APK file is offered for download in a compressed form.
You can just generate one chunk, that would simply be the compressed APK in an archive. Multiple chunks are really only interesting if you want to implement background download.

You can also easily offer multiple versions for download. Each version simply needs its own manifest file.
The app just needs to know which versions exist and where the appropriate update is located.
You can even install third party apps this way. Just note that version downgrades are not possible.

Your use case would be covered by this, or am I misunderstanding? 
Or is it simply that the additional compression step is annoying?

**Comment by capc0** [comment]
I tested it with just one chunk and it is working very well.

> Or is it simply that the additional compression step is annoying?

yes.

The APK file format is already pretty compressed. In my example the APK is 14 MB and the ZIP with one chunk ~13.5 MB.

When releasing a new version of the App, I have to

1. Upload the APK. This is e.g. needed for new users who never downloaded the App before (and of course want to start with the newest version, why bother downloading a outdated verison?)
2. Upload the chunked ZIP. For users who already have an older version installed and are getting the update from within the app.
3. Upload the manifest.json

Step 2 seems rather unnecessary in my opinion.

Nevertheless this plugin is working great, thanks for your efforts!

**Comment by kolbasa** [comment]
The compression rate depends entirely on the structure of the app. For other apps, the savings can be substantial.

But I get the idea. I'm sure many others will see it that way as well.

I'll add that to the backlog. 
But it's low priority for now, there are other important issues I need to solve at the moment.

**Comment by kolbasa** [comment]
I've been thinking about this. You are right. I overengineered the plugin way too much.
This also made it difficult to maintain.

I have simplified the plugin and removed all the manifest logic. 
I still have to write a proper documentation, but on the `refactoring`-branch you can already test the version.
You can now directly download and install the APK. Zipped files are also supported.

`v2.0.0`:
https://github.com/kolbasa/cordova-plugin-apkupdater/tree/refactoring

Demo-Apk:
https://github.com/kolbasa/cordova-plugin-apkupdater-demo

**Comment by capc0** [comment]
hi, thanks for the update.

I will definitely try this once I find some time for it.

**Comment by kolbasa** [comment]
I think I can close this now. Let me know if you have problems with the new version.
