### ISSUE TITLE
make cordova-plugin-androidx not a hard dependency

### ISSUE THREAD

**Issue by capc0** [kolbasa/cordova-plugin-apkupdater#22]
currently `cordova-plugin-androidx` is a hard dependency of this project as defined in https://github.com/kolbasa/cordova-plugin-apkupdater/blob/master/package.json#L12

However, when using `cordova-android >= 9`, the androidx plugin should actually not be installed (see e.g. https://www.npmjs.com/package/cordova-plugin-androidx or https://cordova.apache.org/announcements/2020/06/29/cordova-android-9.0.0.html)

Is it possible to make the dependy optional? Maybe as a `peerDependency` or just via documentation that it is only needed when using `cordova-android <= 8`

---

Also, is there a reason why the version is marked as `^2.0.0` ? `3.0.0` has been out for a while

**Comment by kolbasa** [comment]
Thank you for pointing it out. That wasn't even on my radar.
I'm also a fan of having as few dependencies as possible.

At the time I implemented this, there was no deprecation notice for `cordova-plugin-androidx`.

So will definitely look at how I can fix that.

**Comment by capc0** [comment]
The easiest way for now would be to bump the version of `cordova-plugin-androidx`   to  `3.0.0`, since at that version the plugin itself checks if `cordova-android <= 8` is installed and only installs itself if that is the case.

https://github.com/dpa99c/cordova-plugin-androidx/issues/5#issuecomment-691443172

**Comment by kolbasa** [comment]
I have now implemented it as stated in the Cordova documentation. See commit above.
I am currently checking whether I can offer AndroidX only as an option in general.

**Comment by kolbasa** [comment]
New version without `cordova-plugin-androidx` is now released.
