### ISSUE TITLE
HTTPS URL returns FileNotFoundException

### ISSUE THREAD

**Issue by lupodellasleppa** [kolbasa/cordova-plugin-apkupdater#23]
Hello again.

I have a problem with the plugin when trying to fetch an updated version from an HTTPS URL.

The update works fine when requesting from my local development server.

I read [here](https://github.com/kolbasa/cordova-plugin-apkupdater/issues/9#issuecomment-687036917) you intentended to add something for the authentication, has there been any progress on that? I couldn't find anything on the documentation.

However, I'm authenticating as you said by inserting username and password directly in the URL (like `https://<username>:<password>@my.url.net/`), but i get a `FileNotFoundException`.

I can access the same exact URL from browser or via cURL, and I'm also making a GET request via axios right before the `check` function which resolves the URL correctly.

Am I doing something wrong?

**Comment by capc0** [comment]
have you tried it without the trailing `/` in the URL?

Based on the code here https://github.com/kolbasa/cordova-plugin-apkupdater/blob/master/src/android/downloader/FileDownloader.java#L26 I suppose that the filename will become `NULL` and things go wrong from there.

**Comment by lupodellasleppa** [comment]
i tried with both `/manifest.json` at the end and without anything.

so i tried:
 - `apks/download/manifest.json`
 - `apks/download`

The tricky part is that i see the correct URL being called in chrome, and if i click on that i can reach the file both on cURL and browser

**Comment by lupodellasleppa** [comment]
Hold on, I think it may actually be a problem with our backend. Sorry for the trouble, i will post here what the problem was for reference to others when we find out what's wrong

**Comment by lupodellasleppa** [comment]
So in the end I found out the problem was the `FileDownloader` class was missing a `connection.setRequestProperty()` method to properly send Basic authentication to the server. I tried with `https://username:password@domain.com/` as I saw you suggested in one issue but that didn't work. Maybe because it's https, or maybe for our nginx configurations, I don't know. But it works using that method.

I went to add an optional `options` argument to the `check()` method. This `options` argument is an object which can contain more configurations (kind of like how `axios` does it). For now, the only configuration is `basicAuth`.

So in case a basic authentication is needed, one could just declare an `options` object like
```javascript
const options = {
  basicAuth: "yourAuthorizationTokenHere"
}
```
and then call the `check` method like this:
```javascript
cordova.plugins.apkupdater.check("https://yourdomain.com", options)
```

I'm going to make a PR for this. I'm very noob at Java so it might not be the best code ever, however I tested it with both
 - HTTPS **with** authentication and
 - HTTP **without** authentication

 The other missing cases would be
 - HTTPS **without** authentication and 
 - HTTP **with** authentication.

 Sadly I cannot perform these tests at the moment, however I feel confident it should work in those scenarios as well.

**Comment by kolbasa** [comment]
Now I feel bad.
I rewrote all the code because it was too complex and hard to maintain.

But I will check how I can integrate the `basicAuth` option.
However, the new version supports encrypted zip files if that is sufficient for your use case.

The documentation is not complete, but you can already test it here:

New version: `v2.0.0`:
https://github.com/kolbasa/cordova-plugin-apkupdater/tree/refactoring

Demo-Apk:
https://github.com/kolbasa/cordova-plugin-apkupdater-demo

**Comment by kolbasa** [comment]
I have now implemented it on the branch `basic-auth` based on your pull request:
https://github.com/kolbasa/cordova-plugin-apkupdater/tree/basic-auth

```
cordova plugin add https://github.com/kolbasa/cordova-plugin-apkupdater#basic-auth
```

```js
await ApkUpdater.download(
    'https://your-update-server.com/update.apk',
    {
        onDownloadProgress: console.log,
        basicAuth: {
            userId: 'username',
            password: 'JtE+es2GcHrjTAEU'
        }
    }
);
```

I will include it in the next release.

**Comment by kolbasa** [comment]
The change is now in version `2.1.0`.

[CHANGELOG.md](https://github.com/kolbasa/cordova-plugin-apkupdater/blob/master/CHANGELOG.md)

If something doesn't work, feel free to reopen the issue.
