### ISSUE TITLE
Kiosk Mode  + plugin apkUpdater V2.0.2

### ISSUE THREAD

**Issue by leoalemao3** [kolbasa/cordova-plugin-apkupdater#27]
I have a project that uses the cordova Kiosk mode plugin, in this app I use your V1.2.3 plugin

after downloading the application is minimized on its own to proceed with the installation of the new version, however when I update the plugin to version 2.02 this does not happen anymore, I receive a successful callback but nothing happens

**Comment by kolbasa** [comment]
The plugin had many breaking changes from version 2.0.0. The complete workflow has been changed.
Have you seen the new Readme?

Otherwise, I would need more details about your implementation.

**Comment by leoalemao3** [comment]
yea,

I updated a project with a new version that does not have the Kiosk Mode plugin and it worked perfectly, using the same code no project that is with the kiosk mode, after downloading it goes through then the promise to install but the application is not minimized to proceed with the installation

**Comment by kolbasa** [comment]
I have an idea.
Can you please try the following version and give me feedback afterwards.
```
cordova plugin add https://github.com/kolbasa/cordova-plugin-apkupdater#kiosk-mode
```

**Comment by leoalemao3** [comment]
It worked !!!!!!!!!!!!!!!!!!


You are the man!!

THANK YOU VERY MUCH, you again saved my project!!! NOTA 10

**Comment by kolbasa** [comment]
Great. I'll add this as an option in version 2.0.3 and let you know when it's in.

**Comment by leoalemao3** [comment]
can i keep using this version normally, and when you update to v2.0.3 i will update again or there will be no need?

**Comment by kolbasa** [comment]
I don't know exactly yet. It must be specified somewhere as an option, because it causes problems in normal use.

So it will look something like:
```js
await ApkUpdater.install({
    newTask: false
});
```

So won't be a big change. Until then, you can use the other branch.

**Comment by leoalemao3** [comment]
OK,

please let me know when your plug undergoes a new change to update in my project, for now I will leave it in this version #kioskmode

**Comment by kolbasa** [comment]
The change is now in version `2.1.0`.
The plugin can now detect the kiosk mode automatically. So no additional setting is needed.

[CHANGELOG.md](https://github.com/kolbasa/cordova-plugin-apkupdater/blob/master/CHANGELOG.md)

If something doesn't work, feel free to reopen the issue.
