### ISSUE TITLE
"Download fail" error on check

### ISSUE THREAD

**Issue by soukicz** [kolbasa/cordova-plugin-apkupdater#4]
Hi,
I am trying to integrate your plugin, but I can't get past "check". I am using this code:

```js
await cordova.plugins.apkupdater.check('https://mobile-storage-assets-simplia.s3-eu-central-1.amazonaws.com/apk/manifest.json')
```

With this error (and no stack trace or anything):
```
Uncaught Download failed
```

I am new to cordova and have no idea how to debug this. Can you please help? :)

(Cordova 8.1.0 on android)

**Comment by kolbasa** [comment]
The 'manifest.json' is added to the URL by the plugin itself.
```javascript
await cordova.plugins.apkupdater.check('https://mobile-storage-assets-simplia.s3-eu-central-1.amazonaws.com/apk')
```
instead of:
```javascript
await cordova.plugins.apkupdater.check('https://mobile-storage-assets-simplia.s3-eu-central-1.amazonaws.com/apk/manifest.json')
```

But I'm glad it came up. I will adjust it so that both paths are accepted.

**Comment by soukicz** [comment]
Thank you! It now works as expected :) I was looking for problem with CORS etc and it was just invalid url :))
