### ISSUE TITLE
Cannot read properties of undefined (reading 'getInstalledVersion')

### ISSUE THREAD

**Issue by noelbank00** [kolbasa/cordova-plugin-apkupdater#44]
Hello! I install this package with Ionic 5 and i has an issue.

![image](https://user-images.githubusercontent.com/63310862/172650771-bf1d059f-67dd-482c-a5b0-07e0f536ff28.png)

Can u help me?

**Comment by kolbasa** [comment]
Sure, that's what I'm here for.

Can you give me the output of `ionic info`. That would be helpful.

**Comment by noelbank00** [comment]
Ionic:
Ionic CLI                     : 6.19.1 ([...]\Roaming\npm\node_modules\@ionic\cli)
Utility:

   cordova-res : not installed globally
   native-run  : 1.6.0

System:

   Android SDK Tools : 26.1.1 ([..]\AppData\Local\Android\Sdk)
   NodeJS            : v16.15.0 (D:\Program Files\nodejs\node.exe)
   npm               : 8.5.5
   OS                : Windows 10

**Comment by kolbasa** [comment]
You need to run the command (`ionic info`) in your ionic project folder.

**Comment by kolbasa** [comment]
So for `Ionic` + `Cordova`, installing the plugin with `ionic cordova plugin add cordova-plugin-apkupdater` should be enough.

I need to update the readme. The `cordova-androidx-build` is actually no longer needed if you use the latest `cordova-android` platform.

Here is a complete example with an empty project:

```bash
# Create empty project directory
ionic start app blank --type=angular --cordova --no-interactive

# Navigate to new project directory
cd app

# Install the ApkUpdater Plugin
ionic cordova plugin add cordova-plugin-apkupdater

# Add Android Platform
ionic cordova platform add android

# Run on device/emulator
ionic cordova run android
```

Once the app is launched then open via Chrome `chrome://inspect/#devices` and inspect the app.
This is the easiest way to check if the plugin was installed correctly.
Simply enter "ApkUpdater" in the console. If everything went smoothly, all available functions should now be listed.

**Comment by noelbank00** [comment]
I do an empty project with ur instructions, but the problem still exist.
![image](https://user-images.githubusercontent.com/63310862/172917295-e974e8be-c2b0-4f81-8c9d-856175bd7613.png)

I push my code the public repository, can u check then?

https://github.com/noelbank00/ionic-apk-updater

Has an ionic-info.txt with the `ionic info` output for more information.

**Comment by kolbasa** [comment]
The project from the public repository is fine. For me the plugin is installed correctly.

```bash
git clone https://github.com/noelbank00/ionic-apk-updater
cd ionic-apk-updater
ionic cordova platform add android
ionic cordova run android
```

Maybe it has something to do with the live reloading (`[webpack-dev-server] Live Reloading enabled.`). 
That's what it looks like when I launch your app.

<img width="770" alt="image" src="https://user-images.githubusercontent.com/3901582/172929920-dce06ae8-ae28-49bc-ac98-20134d3f1b15.png">
