### ISSUE TITLE
Cordova error

### ISSUE THREAD

**Issue by qingshuiling** [kolbasa/cordova-plugin-apkupdater#52]
After the latest version update, Cordova is unable to compile, indicating that the SDK version is less than 30, which is incompatible

**Comment by kolbasa** [comment]
Ah interesting. One moment, I think I know the problem.

**Comment by qingshuiling** [comment]
Thank you for your help. I am waiting for your update. Thank you

**Comment by kolbasa** [comment]
I have removed the change that can affect the compileSdkVersion. It should work again.
Let me know if this fixes the problem.
