### ISSUE TITLE
Trust anchor for certification path not found

### ISSUE THREAD

**Issue by appsdevpk** [kolbasa/cordova-plugin-apkupdater#53]
i have provided the apk path but its https not http, when i click on install button, it gives below error
![image](https://github.com/kolbasa/cordova-plugin-apkupdater/assets/516860/199ba103-eb8e-46b1-aef0-d8626382d543)

**Comment by kolbasa** [comment]
I don't think this is a bug with the plugin itself, but rather a wrong configuration of your download server.
Or it could be your Bluestacks installation. I'm not familiar with it, I use Android Studio for testing. You might have to update the certificates.

The plugin has no problems with `https` as far as I know.

Maybe you can send me your apk URL, then I can take a closer look.

**Comment by appsdevpk** [comment]
here is the url, https://apklist.adpcloud.tk/apks/facebooklite.apk

**Comment by kolbasa** [comment]
As I suspected: you are using a **self-signed certificate**. Android is right to complain about this.
![Screenshot 2023-07-09 at 18 45 57](https://github.com/kolbasa/cordova-plugin-apkupdater/assets/3901582/c8e7e79a-30c0-40e7-9a37-f918d128d56d)


**There are three solutions here:**

1. The correct way: you configure your server correctly with known certificates e.g. with a free one from [Let's Encrypt](https://letsencrypt.org).
2. You switch to an unencrypted connection. You have to specify this in your AndroidManifest.xml (`android:usesCleartextTraffic="true"`).
3. You whitelist your own certificate: [Android Documentation](https://developer.android.com/training/articles/security-config).

The problem has nothing to do with the ApkUpdater plugin itself.

**Comment by appsdevpk** [comment]
thanks for the reply, i forgot to install the certificate, its working now
