### ISSUE TITLE
[FEATURE] Ionic Native Wrapper

### ISSUE THREAD

**Issue by danielehrhardt** [kolbasa/cordova-plugin-apkupdater#7]
Hi
i want to ask if it is fine that i will create a Pull Request at the Ionic Native Project for this Plugin?

Ionic Native is like a Wrapper with Interfaces and stuff like that over Cordova/Capacitor Apps. 

Best,
Daniel

**Comment by kolbasa** [comment]
This is not a problem for me. I would have done it myself. However, I still have to familiarize myself with Ionic. I'm currently working on the Capacitor port. Let me know if there is anything I can do to help.
