### ISSUE TITLE
Download failed and unknown exception

### ISSUE THREAD

**Issue by xacegod** [kolbasa/cordova-plugin-apkupdater#9]
Hi, 
I have problem getting this plugin to work with my application.

Problem:
```
cordova.plugins.apkupdater.check(
            'http://raw.githubusercontent.com/kolbasa/cordova-plugin-apkupdater-demo/master/update/manifest.json',
            function (oResp) {
                console.log(JSON.stringify(oResp, ' ', 2));
            },function (oResp) {
                console.log(JSON.stringify(oResp, ' ', 2));
            }
        );
```
I get: "Unknown exception"

```
cordova.plugins.apkupdater.check(
            'http://10.100.100.60/b/manifest.json',
            function (oResp) {
                console.log(JSON.stringify(oResp, ' ', 2));
            },function (oResp) {
                console.log(JSON.stringify(oResp, ' ', 2));
            }
        );
```
I get: "Download failed"

Without callback I get:
![image](https://user-images.githubusercontent.com/39693502/91987618-98705a80-ed2e-11ea-9cc6-b3676cc6bdf8.png)

This is what I have on 10.100.100.60/b :
![image](https://user-images.githubusercontent.com/39693502/91986881-935edb80-ed2d-11ea-9b15-f536f48921d4.png)

On network it doesn't show that it creates a request for the said file regardless of what I try to do.
I read previous issues (closed) and tried with no manifest at the end, tried with other function calls like download, etc. But since it doesn't have a link to pass it aside from check url, I resorted to simply asking.

Cordova 9.0.0 on Android.

**Comment by kolbasa** [comment]
No problem, I am happy to receive questions. Especially when the error description is so detailed.

First, this is what the response should look like:

![grafik](https://user-images.githubusercontent.com/3901582/92161934-9fcc5c80-ee31-11ea-9869-446728512015.png)

I can't say exactly what is causing the app error in your case. But it shows me that I should improve the error handling significantly. Currently many errors are simply caught under "Unknown Exception".

If you want to see the complete error, you can do it like this (and I also see that I did not document this correctly :D ).
```js
cordova.plugins.apkupdater.setObserver(
    {
        exception: function (message, stack) {
            console.error(message, stack);
        }
    }
);

await cordova.plugins.apkupdater.check('https://raw.githubusercontent.com/kolbasa/cordova-plugin-apkupdater-demo/master/update');
```

Then you get the complete stack. And then I can probably say why the connection does not work.
Here is a sample output:

![grafik](https://user-images.githubusercontent.com/3901582/92162359-54667e00-ee32-11ea-9130-1d711b6e05b4.png)

**Comment by xacegod** [comment]
Hi, thank you for fast reply.
I used it on Android 5.0.1 tablet and got this as response:

![image](https://user-images.githubusercontent.com/39693502/92207523-a4bcfa80-ee89-11ea-86f3-cc3d88f0b6e7.png)
![image](https://user-images.githubusercontent.com/39693502/92207610-ccac5e00-ee89-11ea-8316-ac867449c6f1.png)

This is from mobile running Android 8.1.0:
![image](https://user-images.githubusercontent.com/39693502/92208350-455fea00-ee8b-11ea-99a9-11463c583337.png)

**And success from your code/apk link:**
![image](https://user-images.githubusercontent.com/39693502/92208398-63c5e580-ee8b-11ea-9f7b-0ba519829d71.png)

I have whitelist, and I did add permission internet in config.xml.
![image](https://user-images.githubusercontent.com/39693502/92208041-a0451180-ee8a-11ea-9794-6441e73ae46a.png)

My guess is this won't work with ftp since no authentication options are present? 

I removed clear text from config.xml and used http (not https), tried again, and got it to install but now I get this message on install (8.1.0):
![image](https://user-images.githubusercontent.com/39693502/92213356-b4414100-ee93-11ea-8bc2-22d6030cd44c.png)
![image](https://user-images.githubusercontent.com/39693502/92216892-354e0780-ee97-11ea-95a4-31db3f43a83a.png)


On Android 5.0.1 without clear text and with http updated with no problems.

Since it asked for permission to install, it would be nice to configure it to have it (on install) not to confuse users further. And install without prompt would be nice.

Once you add more information about exception I will continue with debugging.

**Comment by kolbasa** [comment]
Wow, you are a gold mine for improvements :smiley:

The problem with the missing internet authorization is a good point. I will fix that quickly.

On the subject of FTP, yes, that is currently not planned. 
However, password protected access can be controlled directly via the HTTP server.
But I will check if I can add a password restriction.

The url will then look like this:
```
https://<username>:<password>@raw.githubusercontent.com/kolbasa/cordova-plugin-apkupdater-demo/master/update
```

And then the installation problem. This is how it looks like on my end:

![grafik](https://user-images.githubusercontent.com/3901582/92222199-e99f5c00-ee9e-11ea-87a3-6d167ca740ac.png)

```
SyntaxError: missing ) after argument list
```
For me this is an indication that the JavaScript code has a syntax error.
Maybe the problem is your `log` function. Unfortunately I cannot see it in the example above.

Can you tell me the android + cordova version. I can't reproduce it on my end.

**Comment by kolbasa** [comment]
I have found another bug:
https://github.com/kolbasa/cordova-plugin-apkupdater/issues/11

I post this here because you mentioned Android 5 above.

I'm going to tackle all the little problems this weekend.

**Comment by xacegod** [comment]
This is with log function (just takes 3 params and console logs them).

`log = function (a,b,c){console.log(a,b,c)};`
`cordova.plugins.apkupdater.install();`


![image](https://user-images.githubusercontent.com/39693502/92226418-0179de80-eea5-11ea-80ac-3db4988c78a5.png)


Tried with `cordova.plugins.apkupdater.install(log,log)` and without them  `cordova.plugins.apkupdater.install()`. Got error on both (different though)... 

On side note you could update readme to include the hint with password and email.
Cordova 9.0.0 and Android 8.1.0.
 
It downloads it (will need to recheck where) but my guess is when it needs to unzip or install it to crash, maybe more permissions are needed? 
Also this warning could be a clue? 
`DevTools failed to load SourceMap: Could not load content for file:///android_asset/www/plugins/code-push/script/acquisition-sdk.js.map: System error: net::ERR_FILE_NOT_FOUND`

**Comment by kolbasa** [comment]
I can imagine that it is related to this:

![grafik](https://user-images.githubusercontent.com/3901582/92228889-e3ae7880-eea8-11ea-9a3a-57b469036328.png)

I have to take a closer look at the effects of this.
However, I'll be away for 8 hours, then I have time to look at it. :+1:

**Comment by kolbasa** [comment]
I found the problem and fixed it in version `1.2.2`. This place overwrote my config changes:

![grafik](https://user-images.githubusercontent.com/3901582/92324988-31f97e00-f047-11ea-8d76-b573d08d819e.png)

Here is an example to test the complete process with one copy and paste:

```javascript
cordova.plugins.apkupdater.setObserver(
    {
        downloadProgress: console.log,
        exception: console.error
    }
);
cordova.plugins.apkupdater.check(
    'https://raw.githubusercontent.com/kolbasa/cordova-plugin-apkupdater-demo/master/update',
    function () {
        cordova.plugins.apkupdater.download(
            function () {
                cordova.plugins.apkupdater.install(console.log, console.error);
            },
            console.error
        );
    },
    console.error
);
```

It looks like this with Android 8:

![android-8](https://user-images.githubusercontent.com/3901582/92325043-ac2a0280-f047-11ea-8faf-5662c8f43f11.gif)

**Comment by den1a** [comment]
Hi. I couldn't find a solution to update the app for a long time. But I found your plugin. There were problems, but I found the solution on this page. Thank you to the author for the complete answers! I'll give you a star!

**Comment by kolbasa** [comment]
Thank you. If problems arise, just let me know. 
But this issue can be closed. This is fixed.
